networks:
  otms-network:
    name: otms-network
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  scylladb-data:
  elasticsearch-data:

services:

  scylladb:
    image: 478mkharb/otms-scylladb:latest
    container_name: scylladb

    command: --smp 1 --memory 1G --overprovisioned 1 --developer-mode 1

    ports:
      - "9042:9042"

    volumes:
      - scylladb-data:/var/lib/scylla

    networks:
      - otms-network

    restart: unless-stopped

  postgres:
    image: 478mkharb/otms-postgres:latest
    container_name: postgres

    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

    ports:
      - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

    networks:
      - otms-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d attendance_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: 478mkharb/otms-redis:latest
    container_name: redis

    command: redis-server --appendonly yes

    ports:
      - "6379:6379"

    volumes:
      - redis-data:/data

    networks:
      - otms-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  elasticsearch:
    image: 478mkharb/otms-elasticsearch:latest
    container_name: elasticsearch

    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ports:
      - "9200:9200"
      - "9300:9300"

    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

    networks:
      - otms-network

    restart: unless-stopped

    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:9200 >/dev/null || exit 1"]
      interval: 20s
      timeout: 10s
      retries: 10