from pydantic import BaseModel, Field


class AskRequest(BaseModel):
    question: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="Natural language question for the AI Assistant.",
        examples=["Why is Employee API slow?"],
    )


class AskResponse(BaseModel):
    answer: str = Field(
        ...,
        description="Response generated by the AI Assistant.",
    )