server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker

    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s

    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: container
        replacement: '$1'

      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: job
        replacement: '$1'

      - source_labels: ['__meta_docker_container_log_stream']
        target_label: stream

      - source_labels: ['__meta_docker_container_id']
        target_label: container_id

    pipeline_stages:

      # Unwrap Docker log format
      - docker: {}

      # Parse your application JSON
      - json:
          expressions:

            # Common
            timestamp: timestamp
            time: time
            level: level
            severity: severity
            message: message
            service: service

            trace_id: trace_id
            span_id: span_id

            # OpenTelemetry
            http_method: '"http.method"'
            http_route: '"http.route"'
            http_target: '"http.target"'
            http_status_code: '"http.status_code"'
            client_address: '"client.address"'
            latency_ns: latency_ns

            # NGINX
            request_method: request_method
            request_uri: request_uri
            request: request
            status: status
            bytes_sent: bytes_sent
            request_time: request_time
            upstream_addr: upstream_addr
            upstream_status: upstream_status
            upstream_response_time: upstream_response_time
            referer: referer
            user_agent: user_agent
            traceparent: traceparent
            tracestate: tracestate
            baggage: baggage

      - labels:
          service:
          level:

      - timestamp:
          source: time
          format: RFC3339
          action_on_failure: skip

      - timestamp:
          source: timestamp
          format: RFC3339
          action_on_failure: skip