import json
from typing import Any


class LokiNormalizer:
    """
    Converts raw Loki log streams into compact observability evidence.

    Logs are grouped by service, endpoint, HTTP status, and
    status classification so repetitive log entries do not
    unnecessarily increase the AI prompt size.
    """

    # Requests at or above this latency are considered slow.
    SLOW_REQUEST_THRESHOLD_MS = 500

    # Endpoints normally generated by monitoring systems.
    MONITORING_ENDPOINTS = {
        "/metrics",
        "/health",
        "/actuator/health",
        "/actuator/prometheus",
    }

    def normalize(
        self,
        data: dict[str, Any],
    ) -> list[dict[str, Any]]:
        """
        Normalize and compact Loki query_range response.

        Only valid HTTP observability records are included.

        Requests are grouped by:
            - service
            - endpoint
            - HTTP status
            - status classification

        A representative trace/span ID is preserved for each group.
        """

        groups: dict[
            tuple[str, str, Any, str],
            list[dict[str, Any]],
        ] = {}

        results = (
            data.get("data", {})
            .get("result", [])
        )

        for stream in results:

            stream_labels = stream.get(
                "stream",
                {},
            )

            default_service = (
                stream_labels.get("service_name")
                or stream_labels.get("service")
                or stream_labels.get("job")
                or "unknown"
            )

            values = stream.get(
                "values",
                [],
            )

            for _, raw_log in values:

                parsed_log = self._parse_log(
                    raw_log
                )

                if not parsed_log:
                    continue

                # --------------------------------------------------
                # Service
                # --------------------------------------------------

                service = (
                    parsed_log.get("service.name")
                    or parsed_log.get("service")
                    or default_service
                )

                # --------------------------------------------------
                # HTTP method
                # --------------------------------------------------

                method = (
                    parsed_log.get("http.method")
                    or parsed_log.get("http_method")
                    or parsed_log.get("method")
                )

                # --------------------------------------------------
                # Endpoint
                #
                # Different OTMS services currently expose
                # different field names.
                # --------------------------------------------------

                endpoint = (
                    parsed_log.get("http.route")
                    or parsed_log.get("http.target")
                    or parsed_log.get("request_uri")
                    or parsed_log.get("endpoint")
                )

                # No endpoint means this is not a useful
                # HTTP observability record.
                if not endpoint:
                    continue

                if not isinstance(endpoint, str):
                    continue

                # Remove query string.
                endpoint = endpoint.split(
                    "?",
                    1,
                )[0]

                # --------------------------------------------------
                # HTTP status
                # --------------------------------------------------

                status_code = (
                    parsed_log.get("http.status_code")
                    or parsed_log.get("status_code")
                    or parsed_log.get("status")
                )

                # No HTTP status means this is not a complete
                # HTTP observability record.
                if status_code is None:
                    continue

                # --------------------------------------------------
                # Status classification
                # --------------------------------------------------

                status_type = self._classify_status(
                    status_code
                )

                # --------------------------------------------------
                # Latency
                #
                # employee-api:
                #     latency_ns
                #
                # attendance-api /
                # notification-api:
                #     latency_ms
                # --------------------------------------------------

                latency_ms = self._extract_latency_ms(
                    parsed_log
                )

                # --------------------------------------------------
                # Trace / Span IDs
                # --------------------------------------------------

                trace_id = (
                    parsed_log.get("trace_id")
                    or parsed_log.get("trace.id")
                )

                span_id = (
                    parsed_log.get("span_id")
                    or parsed_log.get("span.id")
                )

                # --------------------------------------------------
                # Traffic classification
                # --------------------------------------------------

                traffic_type = self._classify_traffic(
                    endpoint
                )

                # --------------------------------------------------
                # Group records
                # --------------------------------------------------

                key = (
                    service,
                    endpoint,
                    status_code,
                    status_type,
                )

                groups.setdefault(
                    key,
                    [],
                ).append(
                    {
                        "method": method or "UNKNOWN",
                        "latency_ms": latency_ms,
                        "trace_id": trace_id,
                        "span_id": span_id,
                        "traffic_type": traffic_type,
                    }
                )

        # ----------------------------------------------------------
        # Build compact normalized evidence
        # ----------------------------------------------------------

        normalized: list[dict[str, Any]] = []

        for (
            service,
            endpoint,
            status_code,
            status_type,
        ), requests in groups.items():

            latencies = [
                request["latency_ms"]
                for request in requests
                if request["latency_ms"] is not None
            ]

            representative = requests[0]

            item: dict[str, Any] = {
                "service": service,
                "method": representative["method"],
                "endpoint": endpoint,
                "status": status_code,
                "status_type": status_type,
                "traffic_type": representative[
                    "traffic_type"
                ],
                "request_count": len(requests),
                "representative_trace_id": (
                    representative["trace_id"]
                ),
                "representative_span_id": (
                    representative["span_id"]
                ),
            }

            # ------------------------------------------------------
            # Latency statistics
            # ------------------------------------------------------

            if latencies:

                min_latency = min(latencies)
                max_latency = max(latencies)
                avg_latency = (
                    sum(latencies) / len(latencies)
                )

                item["min_latency_ms"] = round(
                    min_latency,
                    2,
                )

                item["max_latency_ms"] = round(
                    max_latency,
                    2,
                )

                item["avg_latency_ms"] = round(
                    avg_latency,
                    2,
                )

                if (
                    max_latency
                    >= self.SLOW_REQUEST_THRESHOLD_MS
                ):
                    item["performance"] = "slow"
                else:
                    item["performance"] = "normal"

            else:
                item["performance"] = "unknown"

            # ------------------------------------------------------
            # Error classification
            # ------------------------------------------------------

            if status_type in {
                "client_error",
                "server_error",
            }:
                item["error"] = True
            else:
                item["error"] = False

            normalized.append(item)

        return normalized

    # ==============================================================
    # Helper methods
    # ==============================================================

    def _parse_log(
        self,
        raw_log: str,
    ) -> dict[str, Any] | None:
        """
        Parse a JSON-formatted Loki log line.
        """

        try:
            result = json.loads(raw_log)

            if isinstance(result, dict):
                return result

        except (
            json.JSONDecodeError,
            TypeError,
        ):
            return None

        return None

    def _extract_latency_ms(
        self,
        parsed_log: dict[str, Any],
    ) -> float | None:
        """
        Extract latency and normalize it to milliseconds.

        Supported formats:

            latency_ns
                Nanoseconds -> milliseconds

            latency_ms
                Already milliseconds
        """

        # ----------------------------------------------------------
        # Nanoseconds
        # ----------------------------------------------------------

        latency_ns = parsed_log.get(
            "latency_ns"
        )

        if latency_ns is not None:

            try:
                return round(
                    float(latency_ns) / 1_000_000,
                    2,
                )

            except (
                TypeError,
                ValueError,
            ):
                pass

        # ----------------------------------------------------------
        # Milliseconds
        # ----------------------------------------------------------

        latency_ms = parsed_log.get(
            "latency_ms"
        )

        if latency_ms is not None:

            try:
                return round(
                    float(latency_ms),
                    2,
                )

            except (
                TypeError,
                ValueError,
            ):
                pass

        return None

    def _classify_status(
        self,
        status_code: Any,
    ) -> str:
        """
        Classify an HTTP response status code.
        """

        try:
            status = int(status_code)

        except (
            TypeError,
            ValueError,
        ):
            return "unknown"

        if status >= 500:
            return "server_error"

        if status >= 400:
            return "client_error"

        if status >= 300:
            return "redirect"

        if status >= 200:
            return "success"

        return "unknown"

    def _classify_traffic(
        self,
        endpoint: Any,
    ) -> str:
        """
        Classify traffic as monitoring, business, or unknown.

        Monitoring endpoints include:
            /metrics
            /health
            /actuator/health
            /actuator/prometheus
        """

        if not isinstance(endpoint, str):
            return "unknown"

        if not endpoint:
            return "unknown"

        endpoint = endpoint.split(
            "?",
            1,
        )[0]

        # Exact monitoring endpoints.
        if endpoint in self.MONITORING_ENDPOINTS:
            return "monitoring"

        # Generic actuator endpoints.
        if endpoint.startswith(
            "/actuator/"
        ):
            return "monitoring"

        # Metrics endpoints.
        if endpoint.endswith(
            "/metrics"
        ):
            return "monitoring"

        # Health endpoints.
        if endpoint.endswith(
            "/health"
        ):
            return "monitoring"

        return "business"