{
 "title": "OTMS Application Performance",
 "tags": [
  "otms",
  " performance",
  "application",
  "monitoring"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Application Runtime Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Employee",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"employee-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attendance ",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"attendance-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salary",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{job=\"salary-api\",area=\"heap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"notification-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Employee CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"employee-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attendance CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"attendance-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salary CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "process_cpu_usage{job=\"salary-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification CPU",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"notification-api\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Employee Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"employee-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attendance  Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"attendance-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salary Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"salary-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"notification-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Employee Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(gin_request_duration_count{job=\"employee-api\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attendance Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_total{job=\"attendance-api\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salary Requests/sec",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"salary-api\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Application Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Employee",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(gin_request_duration_count{job=\"employee-api\",status=~\"4..|5..\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Attendance ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{job=\"attendance-api\",status=~\"4..|5..\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Salary",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{job=\"salary-api\",status=~\"4..|5..\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notification",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{job=\"notification-api\",status=~\"4..|5..\"}[5m])) or vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}