apiVersion: 1

datasources:
  - name: Prometheus
    # UID synchronized with all dashboard JSON files.
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true